### ISSUE TITLE
bbq.web.SwfEmbed doesn't fire advertised "onLoad" event

### ISSUE THREAD

**Issue by alanshaw** [achingbrain/bbq#3]
There is a private function "_loaded" which seems to start a periodic check (and fire the event if loaded), but it doesn't seem to be called anywhere.

**Comment by achingbrain** [comment]
This method should be called by the SWF loaded by the SwfEmbed at the end of it's constructor (the docs are uh, opaque on this, sorry).

The reason being that things like exposing internal AS3 methods to JavaScript via ExternalInterface is done at runtime - if we dispatch the onLoad event as soon as the SWF is loaded it will be before the constructor has completed - if any JavaScript depends on internal methods being made available via ExternalInterface it will fail.

What would be better is if the Flash Player dispatched some sort of DOM event after the constructor of the SWF main class has run, but I can't find any reference to any such event, then we can ditch the dependency on calling _loaded.  Off the top of your head, do you know of one?

**Comment by alanshaw** [comment]
Thanks for the clarification. I know of no such event, but I do agree it would be preferable to use something like that.
