### ISSUE TITLE
[Suggestion] CSS file naming

### ISSUE THREAD

**Issue by alanshaw** [achingbrain/bbq#5]
Would it be possible for CSS files to be named package/path/ClassName.css rather than package/path/ClassName/style.css. It would certainly make it easier to bring up the relevant CSS file for a class when using cmd+shift+n in Intellij.

**Comment by achingbrain** [comment]
It's pretty clumsy, I admit, but what about the images?  The idea is you have:

package/path/ClassName/style.css
package/path/ClassName/icon.png
package/path/ClassName/bg.png

etc.

**Comment by achingbrain** [comment]
I guess you could have:

package/path/ClassName/ClassName.css
package/path/ClassName/icon.png
package/path/ClassName/bg.png

which would solve the problem.

**Comment by alanshaw** [comment]
I didn't realise you were meant to put images in there as well.

"ClassName/ClassName.css" feels redundant but is better...especially when I have around 10 tabs open, each of them titled "style.css".
