### ISSUE TITLE
Unexpected side effect bbq.domain.Entity.registerListener

### ISSUE THREAD

**Issue by alanshaw** [achingbrain/bbq#9]
If an entity has not "loaded", calling registerListener has the unexpected side effect of calling loadData if the event type is "onDataLoaded".

Whilst I agree that the callback should be called immediately if the object is loaded, I don't agree with the side effect. My initial reaction was to register the listener and then call loadData explicitly when I wanted to start the load.

Also, just another minor point: This method is documented as private - should it be? If so then it should probably start with an underscore to follow convention and if not we should get rid of the annotation so that it appears in the jsdocs.

**Comment by achingbrain** [comment]
A fair point.  It shouldn't have been marked private either.

For what it's worth, you'd usually not call loadData directly - instead you'd use getPropertyDisplay to display properties of Entities which internally calls loadData where necessary.  Unless of course you explicitly need to call getXYZ in which case yes, you would call loadData first.

I see this as a little like Hibernate/JPA where there are several actions you can take on a persisted entity which causes a database hit - accessing a collection or some other property which is stored in a different table for example (of course a big difference is that Hibernate can fetch the missing data synchronously which is a non-starter for an AJAX request as the browser will lock up, hence all the messing around with onDataLoaded events).  Either way, the ORM layer manages when the data store is hit, not the developer.

I've updated the domain object's guide page to reflect this and am about to push a new version to the repo.
